project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/exercises.Rmd"
    - "!slides/[0-9]*.qmd"
    
website:
  page-navigation: true
  title: "Workshop Title"
  description: "Homepage for  Workshop"
  site-url: "https://www.github.com/hossainlab"
  favicon: "images/trans - gt.png"
  
  repo-url: https://github.com/hossainlab/clinical-reporting-gtsummary-rmed
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@hossainlab"
    image: "/images/two-hex-logo.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Md. Jubayer Hossain"
    background: "#708090"

  sidebar:
    background: "#708090"
    logo: "images/trans - gt.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/hossainlab/
        text: GitHub
        
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: material.qmd
     - href: q-and-a.qmd
       text: Workshop Q & A
     - href: license.qmd
       text: License

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

